name: Deploy Next.js site (pnpm) in `website/` to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: website
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js with pnpm cache
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: pnpm
          cache-dependency-path: website/pnpm-lock.yaml

      - name: Install pnpm CLI
        uses: pnpm/action-setup@v2
        with:
          version: v7

      - name: Configure Pages for Next.js
        uses: actions/configure-pages@v5
        with:
          static_site_generator: next

      - name: Restore Next.js build cache
        uses: actions/cache@v4
        with:
          path: website/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('website/pnpm-lock.yaml') }}-${{ hashFiles('website/**/*.[jt]s','website/**/*.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('website/pnpm-lock.yaml') }}-

      - name: Install dependencies
        run: pnpm install

      - name: Build & export
        run: |
          pnpm exec next build
          pnpm exec next export -o out

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: website/out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
