name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: |
          rm -f pnpm-lock.yaml
          pnpm install
        working-directory: website

      - name: Build with Next.js
        run: |
          export NODE_ENV=production
          export NEXT_TELEMETRY_DISABLED=1
          export NEXT_PUBLIC_BASE_PATH=""
          export NEXT_SHARP_PATH=""
          
          # Build the application
          pnpm run build
          
          # Ensure CSS files are properly copied
          if [ -d ".next/static/css" ]; then
            mkdir -p out/_next/static/css
            cp -r .next/static/css/* out/_next/static/css/
            echo "CSS files copied successfully"
          else
            echo "No CSS files found in .next/static/css"
          fi
        working-directory: website
        env:
          NODE_ENV: production
          NEXT_TELEMETRY_DISABLED: 1
          NEXT_PUBLIC_BASE_PATH: ""
          NEXT_SHARP_PATH: ""

      - name: Verify build output
        run: |
          echo "Checking build output..."
          ls -la out/
          echo "Checking for CSS files..."
          find out/ -name "*.css" -type f
          echo "Checking for HTML files..."
          find out/ -name "*.html" -type f | head -5
          echo "Checking .next directory..."
          ls -la .next/static/css/ || echo "No .next/static/css directory"
          echo "Checking if CSS is referenced in HTML..."
          grep -r "\.css" out/ | head -3 || echo "No CSS references found"
        working-directory: website

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: website/out  # Output directory for static export

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
